[package]
name = "flutter_quickjs_bridge"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
[dependencies]
flatbuffers = "25.2.10"
quickjs-rusty = "0.7.2"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
